# Generated by Django 6.0 on 2025-12-11 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num1', models.FloatField()),
                ('num2', models.FloatField(blank=True, null=True)),
                ('operation', models.CharField(choices=[('add', 'Сложение'), ('subtract', 'Вычитание'), ('multiply', 'Умножение'), ('divide', 'Деление'), ('power', 'Возведение в степень'), ('sqrt', 'Квадратный корень')], max_length=20)),
                ('result', models.FloatField()),
                ('expression', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='calculator__user_id_0cd1f7_idx'), models.Index(fields=['created_at'], name='calculator__created_0c5e9d_idx')],
            },
        ),
    ]
